# Generated by Django 4.1.3 on 2023-01-18 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Uncategorised', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/profile_image/')),
                ('image_id', models.ImageField(upload_to='media/profile_id_image/')),
                ('phone_number', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('district', models.CharField(blank=True, max_length=200, null=True)),
                ('rate_range', models.CharField(blank=True, choices=[('$10-$20', '$10-$20'), ('$20-$30', '$20-$30'), ('$30-$40', '$30-$40'), ('$40-$50', '$40-$50'), ('$50+', '$50+')], max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Not Authenticated'), (1, 'Authenticated')], default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busy_from', models.DateField()),
                ('busy_until', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubHazApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='static/featured_image/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', tinymce.models.HTMLField()),
                ('excerpt', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SubHazApp.category')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
