# Generated by Django 4.1.3 on 2023-01-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubHazApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.AlterField(
            model_name='profile',
            name='rate_range',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
