# Generated by Django 4.1.3 on 2023-01-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubHazApp', '0002_remove_profile_district_alter_profile_rate_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
