# Generated by Django 4.1.3 on 2023-01-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubHazApp', '0003_profile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='region',
            new_name='city',
        ),
    ]
