# Generated by Django 4.1.3 on 2023-01-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubHazApp', '0004_rename_region_profile_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rate_range',
            new_name='charge_rate',
        ),
    ]
