# Generated by Django 4.1.3 on 2023-01-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SubHazApp', '0005_rename_rate_range_profile_charge_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unavailability',
        ),
    ]
